### ISSUE TITLE
Enable flagging an account as producer owned

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/power-user-script#1]
http://world.openfoodfacts.org/contributor/*
It would go to a dedicated spreadsheet, so that we can systematically contact them

**Comment by CharlesNepote** [comment]
It would be better not to add a new spreadsheet and use filters with the existing one. We can already flag a revision with "pro_account". What is the issue with the current spreadsheet or process?

May be I can allow flagging in a user account page such as https://world.openfoodfacts.org/contributor/charlesnepote ? Is that what you want?
