### ISSUE TITLE
Allow to display barcodes when listing products

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/power-user-script#26]
Allow to display all barcodes when listing products.

We could accept "shift+b" keyboard shortcut when listing products.

**Comment by svensven** [comment]
does this mean show just the numbers, or a graphical barcode?

**Comment by CharlesNepote** [comment]
A graphical barcode. The barcode library is already loaded by default, see `@require     https://cdn.jsdelivr.net/jsbarcode/3.6.0/JsBarcode.all.min.js`.

Use cases:
* test Open Food Facts apps with many products
* control if an app is using Open Food Facts or not
* make a demo of Open Food Facts apps (or other apps)
* etc.
