### ISSUE TITLE
Deep link to Hunger Games from Facets pages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/power-user-script#27]
Deep link to Hunger Games from Facets pages to increase contributions
https://hunger.openfoodfacts.org/questions?type=brand&value_tag=whole-foods-market
https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Aorganic
https://hunger.openfoodfacts.org/questions?type=category&value_tag=en%3Aalcoholic-beverages

**Comment by teolemon** [comment]
This is very important on this facet: https://fr.openfoodfacts.org/ciqual-food-names to help drive an effort for the Eco-Score

**Comment by CharlesNepote** [comment]
Feature is ok for brands, labels and categories facets.
