### ISSUE TITLE
List mode seems to be broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/power-user-script#76]
### What
List mode seems to be broken
```
[22:59](https://openfoodfacts.slack.com/archives/CDC9K6RFT/p1672437596559249)
benbenben
 How to move Open Beauty Facts products into Open Beauty Facts? (I am moderator)
(shift + L seems to not be an option anymore: https://wiki.openfoodfacts.org/Open_Beauty_Facts)
```

**Comment by CharlesNepote** [comment]
Power User Script is working well in fact. The "-> OBF" button is just a link: api call-> https://world.openfoodfacts.org/cgi/product_jqm.pl?type=edit&code=0842379199042&new_code=obf

But when a product already exists in OBF, the move fails (and many products you will want to move already exist). When a product do exists, the answer from Product Opener is:
`{ status: 0, status_verbose: "new code is invalid" }` 
but I'm not sure that this means the product already exist or that there are other kinds of issues.

I can change the "Failed!" message by "Existing product. Can't move!" if I'm sure about it.

**Comment by teolemon** [comment]
I had an obsolete version of the User Script.
